version: '3'

services:
  # https://geshan.com.np/blog/2022/01/redis-docker/
  redis:
    image: redis
    restart: always
    ports:
      - '9736:6379'
    command: redis-server --save 60 1 --loglevel warning
    # volumes: 
    #   - cache:/data

  # https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'go_test_models'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'jiayu'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'jiayu'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '6033:3306'
    # expose:
      # Opens port 3306 on the container
      # - '3306'
      # Where our data will be persisted
    # volumes:
    #   - db:/var/lib/mysql

  # volumes:
  #   db:
  #     driver: local
  #   redis:
  #     driver: local

  api:
    image: gin-gorm-redis-api
    ports:
      - 8000:8000
    expose:
      # Opens port 3306 on the container
      - '8000'
    links:
      - redis
      - db
    # restart: on-failure
    restart: always
    depends_on:
      - redis
      - db
